
const SKEY='chfc_stats_v1';
const seasonSelect=document.getElementById('seasonSelect');
const statsBody=document.getElementById('statsBody');
const form=document.getElementById('statForm');
const addSeasonBtn=document.getElementById('addSeasonBtn');
function loadLocal(){ try{ return JSON.parse(localStorage.getItem(SKEY))||null; }catch(e){ return null; }}
function saveLocal(d){ localStorage.setItem(SKEY, JSON.stringify(d)); }
async function getSeed(){ const seed=await fetch('data/stats.json').then(r=>r.json()); const local=loadLocal(); return local||seed; }
function ensureSeason(d,label){ if(!d.seasons) d.seasons=[]; let s=d.seasons.find(x=>x.season===label); if(!s){ s={season:label, players:[]}; d.seasons.push(s);} return s; }
function aggregate(players){ const by={}; for(const p of players){ const k=(p.name||'').trim().toLowerCase(); if(!k) continue; if(!by[k]) by[k]={name:p.name,number:p.number||'',pos:p.pos||'',gp:0,g:0,a:0,pts:0,cs:0,yc:0,rc:0,mins:0}; const t=by[k]; t.gp+=(p.gp||0); t.g+=(p.g||0); t.a+=(p.a||0); t.cs+=(p.cs||0); t.yc+=(p.yc||0); t.rc+=(p.rc||0); t.mins+=(p.mins||0); t.pts=t.g*2+t.a; } return Object.values(by).sort((x,y)=> y.pts-x.pts || y.g-x.g); }
function renderTable(rows){ let html=''; for(const r of rows){ html+='<tr><td>'+r.name+'</td><td>'+r.gp+'</td><td>'+r.g+'</td><td>'+r.a+'</td><td>'+r.pts+'</td><td>'+r.cs+'</td><td>'+r.yc+'</td><td>'+r.rc+'</td><td>'+r.mins+'</td></tr>'; } statsBody.innerHTML=html; }
async function init(){ const data=await getSeed(); seasonSelect.innerHTML=data.seasons.map(s=>'<option value="'+s.season+'">'+s.season+'</option>').join(''); if(!seasonSelect.value && data.seasons[0]) seasonSelect.value=data.seasons[0].season; const cur=data.seasons.find(s=>s.season===seasonSelect.value)||data.seasons[0]; renderTable(aggregate(cur.players||[])); seasonSelect.addEventListener('change',()=>{ const d=loadLocal()||data; const ssn=(d.seasons.find(s=>s.season===seasonSelect.value)||{players:[]}); renderTable(aggregate(ssn.players)); }); addSeasonBtn.addEventListener('click',()=>{ const label=prompt('New season name (e.g., Spring 2026)'); if(!label) return; const d=loadLocal()||data; ensureSeason(d,label); saveLocal(d); seasonSelect.innerHTML=d.seasons.map(s=>'<option value="'+s.season+'">'+s.season+'</option>').join(''); seasonSelect.value=label; renderTable([]); }); form.addEventListener('submit',async (e)=>{ e.preventDefault(); const entry={ name:document.getElementById('player').value.trim(), number:'', pos:'', gp:1, g:parseInt(document.getElementById('goals').value||'0',10), a:parseInt(document.getElementById('assists').value||'0',10), cs:parseInt(document.getElementById('cs').value||'0',10), yc:parseInt(document.getElementById('yc').value||'0',10), rc:parseInt(document.getElementById('rc').value||'0',10), mins:parseInt(document.getElementById('mins').value||'0',10), date:document.getElementById('gdate').value, opponent:document.getElementById('opponent').value, notes:document.getElementById('notes').value }; const d=loadLocal()||await getSeed(); const s=ensureSeason(d, seasonSelect.value || (d.seasons[0]&&d.seasons[0].season) || 'Season'); s.players.push(entry); saveLocal(d); if(window.STATS_ENDPOINT){ try{ await fetch(window.STATS_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({season:s.season,entry})}); }catch(err){ console.warn('Remote save failed:',err); }} renderTable(aggregate(s.players)); form.reset(); }); }
init();
